name: Build iOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install ldid
        run: brew install ldid

      - name: Build & Sign
        run: make -f Makefile-ios

      - uses: actions/upload-artifact@v4
        with:
          name: gh-ios
          path: gh
